#!/bin/bash
for i in 8 16 32; do
< /dev/urandom tr -dc A-Za-z0-9_ | head -c$i
echo 
done
for i in {1..3}; do 
    echo -n `grep -v \' /usr/share/dict/british-english | sort -R | head -n 2 | sed ':a;N;$!ba;s/\n//g'`
    < /dev/urandom tr -dc 0-9 | head -c2
    echo ''
done
